defaults:
  - _self_

hydra:
  run:
    dir: /pfs/work7/workspace/scratch/fr_pb278-masters_project//outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}  
  job:
    chdir: false

wandb:
  project_name: CANDID_DAC
  tags: null

track_training:
  # display a progress bar to stdout during training
  disable_pbar: true
  # store model checkpoints of policies during training
  store_ckpts: true
  # evaluate greedy policy on training set every 100 episodes
  eval_train: true
  # evaluate greedy policy on test set every 100 episodes
  eval_test: true
  # compute value of initial state of an episode 
  predict_initial_v: true
  results_dir: /pfs/work7/workspace/scratch/fr_pb278-masters_project/

total_episodes: 10000
seed: null
